//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosTExData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataprovidercache
    {
        public long id { get; set; }
        public string source { get; set; }
        public System.DateTime date { get; set; }
        public string data { get; set; }
    }
}
