//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class achievement_reward
    {
        public int entry { get; set; }
        public sbyte gender { get; set; }
        public int title_A { get; set; }
        public int title_H { get; set; }
        public int item { get; set; }
        public int sender { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
    }
}
