//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_spells
    {
        public int entry { get; set; }
        public int spell1 { get; set; }
        public int spell2 { get; set; }
        public int spell3 { get; set; }
        public int spell4 { get; set; }
        public int spell5 { get; set; }
        public int spell6 { get; set; }
        public int spell7 { get; set; }
        public int spell8 { get; set; }
    }
}
