//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_model_race
    {
        public int modelid { get; set; }
        public int racemask { get; set; }
        public int creature_entry { get; set; }
        public int modelid_racial { get; set; }
    }
}
