//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_addon
    {
        public long guid { get; set; }
        public float path_rotation0 { get; set; }
        public float path_rotation1 { get; set; }
        public float path_rotation2 { get; set; }
        public float path_rotation3 { get; set; }
    }
}
