//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_poi
    {
        public int questId { get; set; }
        public byte poiId { get; set; }
        public int objIndex { get; set; }
        public long mapId { get; set; }
        public int mapAreaId { get; set; }
        public byte floorId { get; set; }
        public long unk3 { get; set; }
        public long unk4 { get; set; }
    }
}
