//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_template
    {
        public long id { get; set; }
        public long attr { get; set; }
        public long attr_ex { get; set; }
        public long attr_ex2 { get; set; }
        public long proc_flags { get; set; }
        public long proc_chance { get; set; }
        public long duration_index { get; set; }
        public long effect0 { get; set; }
        public long effect0_implicit_target_a { get; set; }
        public long effect0_implicit_target_b { get; set; }
        public long effect0_radius_idx { get; set; }
        public long effect0_apply_aura_name { get; set; }
        public long effect0_misc_value { get; set; }
        public long effect0_misc_value_b { get; set; }
        public long effect0_trigger_spell { get; set; }
        public string comments { get; set; }
    }
}
