//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangosData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_accessory
    {
        public long vehicle_entry { get; set; }
        public int seat { get; set; }
        public long accessory_entry { get; set; }
        public string comment { get; set; }
    }
}
