namespace MangosData.Models.Bases
{
    public enum GameObjectType : int
    {
        DOOR = 0,
        BUTTON = 1,
        QUESTGIVER = 2,
        CHEST = 3,
        BINDER = 4,
        GENERIC = 5,
        TRAP = 6,
        CHAIR = 7,
        SPELL_FOCUS = 8,
        TEXT = 9,
        GOOBER = 10,
        TRANSPORT = 11,
        AREADAMAGE = 12,
        CAMERA = 13,
        MAPOBJECT = 14,
        MO_TRANSPORT = 15,
        DUELFLAG = 16,
        FISHINGNODE = 17,
        SUMMONING_RITUAL = 18,
        MAILBOX = 19,
        DONOTUSE = 20,
        GUARDPOST = 21,
        SPELLCASTER = 22,
        MEETINGSTONE = 23,
        FLAGSTAND = 24,
        FISHINGHOLE = 25,
        FLAGDROP = 26,
        MINI_GAME = 27,
        LOTTERYKIOSK = 28,
        CAPTURE_POINT = 29,
        AURA_GENERATOR = 30,
        DUNGEON_DIFFICULTY = 31,
        BARBER_CHAIR = 32,
        DESTRUCTIBLE_BUILDING = 33,
        GUILD_BANK = 34,
        TRAPDOOR = 35,
    }
}
